# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FrequencyOverlaps
                                 A QGIS plugin
 Check for overlapping frequencies in a layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-07
        copyright            : (C) 2021 by Cavin Wang
        email                : kokkang_2000@yahoo.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FrequencyOverlaps class from file FrequencyOverlaps.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .frequency_overlaps import FrequencyOverlaps
    return FrequencyOverlaps(iface)
